import type { WeatherData, ForecastData } from "./types"

// Mock current weather data
export const mockWeatherData: WeatherData = {
  temperature: 22,
  feelsLike: 24,
  minTemp: 18,
  maxTemp: 26,
  humidity: 65,
  pressure: 1012,
  windSpeed: 12,
  windDirection: 220,
  windGust: 18,
  condition: "partly cloudy",
  iconUrl: "/placeholder.svg?height=100&width=100&text=☁️",
  sunrise: "06:45",
  sunset: "19:30",
  dayLength: "12h 45m",
  date: "Monday, June 12",
  precipitation: 2.5,
  rainChance: 30,
}

// Mock forecast data
export const mockForecastData: ForecastData[] = [
  // Daily forecast
  {
    date: "Today",
    temperature: 22,
    minTemp: 18,
    maxTemp: 26,
    condition: "partly cloudy",
    iconUrl: "/placeholder.svg?height=50&width=50&text=☁️",
    rainChance: 30,
    windSpeed: 12,
    isDaily: true,
  },
  {
    date: "Tue",
    temperature: 24,
    minTemp: 19,
    maxTemp: 28,
    condition: "sunny",
    iconUrl: "/placeholder.svg?height=50&width=50&text=☀️",
    rainChance: 10,
    windSpeed: 8,
    isDaily: true,
  },
  {
    date: "Wed",
    temperature: 25,
    minTemp: 20,
    maxTemp: 29,
    condition: "clear",
    iconUrl: "/placeholder.svg?height=50&width=50&text=☀️",
    rainChance: 5,
    windSpeed: 6,
    isDaily: true,
  },
  {
    date: "Thu",
    temperature: 23,
    minTemp: 19,
    maxTemp: 27,
    condition: "cloudy",
    iconUrl: "/placeholder.svg?height=50&width=50&text=☁️",
    rainChance: 40,
    windSpeed: 14,
    isDaily: true,
  },
  {
    date: "Fri",
    temperature: 21,
    minTemp: 17,
    maxTemp: 24,
    condition: "rain",
    iconUrl: "/placeholder.svg?height=50&width=50&text=🌧️",
    rainChance: 80,
    windSpeed: 18,
    isDaily: true,
  },

  // Hourly forecast
  {
    date: "Today",
    time: "Now",
    temperature: 22,
    minTemp: 0,
    maxTemp: 0,
    condition: "partly cloudy",
    iconUrl: "/placeholder.svg?height=50&width=50&text=☁️",
    rainChance: 30,
    windSpeed: 12,
    isDaily: false,
  },
  {
    date: "Today",
    time: "13:00",
    temperature: 24,
    minTemp: 0,
    maxTemp: 0,
    condition: "partly cloudy",
    iconUrl: "/placeholder.svg?height=50&width=50&text=☁️",
    rainChance: 25,
    windSpeed: 10,
    isDaily: false,
  },
  {
    date: "Today",
    time: "14:00",
    temperature: 25,
    minTemp: 0,
    maxTemp: 0,
    condition: "sunny",
    iconUrl: "/placeholder.svg?height=50&width=50&text=☀️",
    rainChance: 15,
    windSpeed: 8,
    isDaily: false,
  },
  {
    date: "Today",
    time: "15:00",
    temperature: 26,
    minTemp: 0,
    maxTemp: 0,
    condition: "sunny",
    iconUrl: "/placeholder.svg?height=50&width=50&text=☀️",
    rainChance: 10,
    windSpeed: 7,
    isDaily: false,
  },
  {
    date: "Today",
    time: "16:00",
    temperature: 25,
    minTemp: 0,
    maxTemp: 0,
    condition: "sunny",
    iconUrl: "/placeholder.svg?height=50&width=50&text=☀️",
    rainChance: 5,
    windSpeed: 6,
    isDaily: false,
  },
  {
    date: "Today",
    time: "17:00",
    temperature: 24,
    minTemp: 0,
    maxTemp: 0,
    condition: "clear",
    iconUrl: "/placeholder.svg?height=50&width=50&text=☀️",
    rainChance: 5,
    windSpeed: 5,
    isDaily: false,
  },
  {
    date: "Today",
    time: "18:00",
    temperature: 23,
    minTemp: 0,
    maxTemp: 0,
    condition: "clear",
    iconUrl: "/placeholder.svg?height=50&width=50&text=☀️",
    rainChance: 5,
    windSpeed: 4,
    isDaily: false,
  },
  {
    date: "Today",
    time: "19:00",
    temperature: 21,
    minTemp: 0,
    maxTemp: 0,
    condition: "clear",
    iconUrl: "/placeholder.svg?height=50&width=50&text=🌙",
    rainChance: 5,
    windSpeed: 3,
    isDaily: false,
  },
  {
    date: "Today",
    time: "20:00",
    temperature: 20,
    minTemp: 0,
    maxTemp: 0,
    condition: "clear",
    iconUrl: "/placeholder.svg?height=50&width=50&text=🌙",
    rainChance: 5,
    windSpeed: 3,
    isDaily: false,
  },
]

